# Generated by Django 3.2.16 on 2022-10-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Arms',
        ),
    ]
