# Generated by Django 3.2.16 on 2022-10-16 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='姓名', max_length=255)),
                ('specialty', models.CharField(help_text='专业', max_length=255)),
                ('studentID', models.CharField(help_text='学号', max_length=255)),
                ('self_introduction', models.TextField(help_text='自我介绍', max_length=500)),
                ('ip', models.CharField(help_text='IP地址', max_length=255)),
                ('last_vercode', models.CharField(help_text='上次邮箱验证码', max_length=255)),
                ('hobby', models.CharField(help_text='爱好的CTF项目', max_length=255)),
                ('UID', models.ForeignKey(help_text='用户UID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
