# Generated by Django 3.2.16 on 2022-10-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20221016_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vercode',
            name='email',
        ),
        migrations.AddField(
            model_name='vercode',
            name='username',
            field=models.CharField(default='error', help_text='用户名', max_length=255),
        ),
    ]
